# Parameters for different critics
critic_params = {
    "CholeskyInput": {
        "num_obs": 10,
        "hidden_dims": [256, 128],
        "activation": "relu",
        "normalize_obs": True,
        "latent_dim": 16,  # 16,
        "minimize": False,
    },
    "PDCholeskyInput": {
        "num_obs": 10,
        "hidden_dims": [256, 128],
        "activation": "relu",
        "normalize_obs": False,
        "latent_dim": None,
        "minimize": False,
    },
    "CholeskyLatent": {
        "num_obs": 10,
        "hidden_dims": [256, 128],
        "activation": "relu",
        "normalize_obs": False,
        "minimize": False,
        "latent_dim": 16,
        "latent_hidden_dims": [64, 64],
        "latent_activation": None,
    },
    "PDCholeskyLatent": {
        "num_obs": 10,
        "hidden_dims": [256, 128],
        "activation": "relu",
        "normalize_obs": False,
        "minimize": False,
        "latent_dim": 16,
        "latent_hidden_dims": [64, 64],
        "latent_activation": None,
    },
    "SpectralLatent": {
        "num_obs": 10,
        "hidden_dims": [256, 128],
        "activation": "relu",
        "normalize_obs": False,
        "minimize": False,
        "relative_dim": 8,
        "latent_dim": 16,
        "latent_hidden_dims": [64, 64],
        "latent_activation": None,
    },
    "DenseSpectralLatent": {
        "num_obs": 10,
        "hidden_dims": [256, 128],
        "activation": "relu",
        "normalize_obs": False,
        "minimize": False,
        "relative_dim": 4,  # 1,
        "latent_dim": 16,  # 18,
        "latent_hidden_dims": [32, 32],
        "latent_activation": None,
    },
    "OuterProduct": {
        "num_obs": 10,
        "hidden_dims": [256, 128],
        "minimize": False,
        "activation": "relu",
        "normalize_obs": False,
    },
    "OuterProductLatent": {
        "num_obs": 10,
        "hidden_dims": [256, 128],
        "activation": "relu",
        "normalize_obs": False,
        "minimize": False,
        "latent_dim": 16,
        "latent_hidden_dims": [32, 32],
        "latent_activation": None,
    },
    "Critic": {
        "num_obs": 10,
        "hidden_dims": [256, 128],
        "activation": "relu",
        "normalize_obs": False,
    },
    "Cholesky": {
        "num_obs": 10,
        "hidden_dims": None,
        "activation": "relu",
        "normalize_obs": False,
    },
    "CholeskyPlusConst": {
        "num_obs": 10,
        "hidden_dims": None,
        "activation": "relu",
        "normalize_obs": False,
    },
    "CholeskyOffset1": {
        "num_obs": 10,
        "hidden_dims": None,
        "activation": "relu",
        "normalize_obs": False,
    },
    "CholeskyOffset2": {
        "num_obs": 10,
        "hidden_dims": None,
        "activation": "relu",
        "normalize_obs": False,
    },
    "QPNet": {
        "num_obs": 10,
        "hidden_dims": [256, 128],
        "activation": "relu",
        "normalize_obs": True,
        "latent_dim": 16,  # 16,
        "minimize": False,
    },
    "NN_wQR": {
        "critic_name": "SpectralLatent",
        "action_dim": 2,
        "regularization": "sequential",  # alternative is "interleaved"
    },
    "NN_wLinearLatent": {
        "critic_name": "DenseSpectralLatent",
        "action_dim": 12,
        "regularization": "sequential",  # alternative is "interleaved"
    },
}
