# Parameters for different critics
critic_params = {
    "CholeskyInput": {
        "num_obs": 2,
        "hidden_dims": [128, 32],
        "activation": ["elu", "elu", "elu"],
        "normalize_obs": True,
        "latent_dim": None,  # 16,
        "minimize": False,
    },
    "PDCholeskyInput": {
        "num_obs": 2,
        "hidden_dims": [128, 32],
        "activation": ["elu", "elu", "elu"],
        "normalize_obs": True,
        "latent_dim": None,  # 16,
        "minimize": False,
    },
    "CholeskyLatent": {
        "num_obs": 2,
        "hidden_dims": [128, 32],
        "activation": ["elu", "elu", "elu"],
        "normalize_obs": False,
        "minimize": False,
        "latent_dim": 16,
        "latent_hidden_dims": [32],
        "latent_activation": ["elu", "elu"],
    },
    "PDCholeskyLatent": {
        "num_obs": 2,
        "hidden_dims": [128, 32],
        "activation": ["elu", "elu", "elu"],
        "normalize_obs": False,
        "minimize": False,
        "latent_dim": 16,
        "latent_hidden_dims": [32],
        "latent_activation": ["elu", "elu"],
    },
    "SpectralLatent": {
        "num_obs": 2,
        "hidden_dims": [128, 32],
        "activation": ["elu", "elu", "elu"],
        "normalize_obs": False,
        "minimize": False,
        "relative_dim": 4,
        "latent_dim": 16,
        "latent_hidden_dims": [128, 64],
        "latent_activation": ["elu", "elu"],
    },
    "Critic": {
        "num_obs": 2,
        "hidden_dims": [128, 32],
        "activation": "elu",
        "normalize_obs": False,
        "output_size": 1,
    },
    "Cholesky": {
        "num_obs": 2,
        "hidden_dims": None,
        "activation": "elu",
        "normalize_obs": False,
        "output_size": 1,
    },
    "CholeskyPlusConst": {
        "num_obs": 2,
        "hidden_dims": None,
        "activation": "elu",
        "normalize_obs": False,
        "output_size": 1,
    },
    "CholeskyOffset1": {
        "num_obs": 2,
        "hidden_dims": None,
        "activation": "elu",
        "normalize_obs": False,
        "output_size": 1,
    },
    "CholeskyOffset2": {
        "num_obs": 2,
        "hidden_dims": None,
        "activation": "elu",
        "normalize_obs": False,
        "output_size": 1,
    },
    "NN_wQR": {
        "critic_name": "SpectralLatent",
        "action_dim": 2,
        "regularization": "sequential",  # alternative is "interleaved"
    },
    "NN_wLinearLatent": {
        "critic_name": "SpectralLatent",
        "action_dim": 2,
        "regularization": "sequential",  # alternative is "interleaved"
    },
}
